# Generated by Django 4.2.7 on 2024-05-07 18:34

from django.db import migrations, models
import django.db.models.deletion
import xpoarena.models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0023_rename_product_paymenthistory_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateOfEvent', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('image', models.ImageField(upload_to=xpoarena.models.upload_to)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpoarena.organization')),
            ],
        ),
    ]
