# Generated by Django 4.2.7 on 2024-05-09 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0024_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
